import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Build output and artefacts — never hand-written, never linted.
    "dist/**",
    "storage/**",
    "playwright-report/**",
    "test-results/**",
    "coverage/**",
    /*
     * Generated by Payload, then reviewed and hand-edited where a constraint
     * needs adding. Their `up`/`down` signatures carry parameters a given
     * migration may not use, which is not a defect worth a warning on every
     * future migration. `pnpm check:migrations` is what actually guards these
     * (DATA-04: only-add).
     */
    "src/migrations/**",
    "src/payload-types.ts",
    "src/app/(payload)/admin/importMap.js",
  ]),
]);

export default eslintConfig;
