import { MigrateUpArgs, MigrateDownArgs, sql } from "@payloadcms/db-postgres";

/**
 * Card payments (PAY-01), and job references that cannot collide.
 *
 * `quotes.stripe_checkout_session_id` — generated by Payload from the Quotes
 * collection. One Checkout Session per quote; the unique index is what makes
 * "one" true under a double-click or two open tabs.
 *
 * `job_reference_seq` — hand-written, because Payload's config cannot express
 * a sequence. Job references were "read the highest, add one", retried on a
 * unique-index collision. The retry could never work: a unique violation
 * aborts the surrounding Postgres transaction, so the second attempt failed
 * with "current transaction is aborted" whatever reference it tried. A
 * sequence hands out numbers outside any transaction and never repeats one.
 *
 * It starts after the highest existing `J-` reference, so a database that
 * already holds jobs carries on from where it was. A rolled-back booking burns
 * a number and leaves a gap; gaps are harmless, duplicates are not.
 */
export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "quotes" ADD COLUMN "stripe_checkout_session_id" varchar;
  CREATE UNIQUE INDEX "quotes_stripe_checkout_session_id_idx" ON "quotes" USING btree ("stripe_checkout_session_id");

  CREATE SEQUENCE IF NOT EXISTS "job_reference_seq" AS bigint MINVALUE 1;
  SELECT setval(
    'job_reference_seq',
    COALESCE(
      (SELECT MAX(substring("reference" FROM 3)::bigint) FROM "jobs" WHERE "reference" ~ '^J-[0-9]+$'),
      0
    ) + 1,
    false
  );`);
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   DROP SEQUENCE IF EXISTS "job_reference_seq";
  DROP INDEX "quotes_stripe_checkout_session_id_idx";
  ALTER TABLE "quotes" DROP COLUMN "stripe_checkout_session_id";`);
}
