/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | "Pacific/Midway"
  | "Pacific/Niue"
  | "Pacific/Honolulu"
  | "Pacific/Rarotonga"
  | "America/Anchorage"
  | "Pacific/Gambier"
  | "America/Los_Angeles"
  | "America/Tijuana"
  | "America/Denver"
  | "America/Phoenix"
  | "America/Chicago"
  | "America/Guatemala"
  | "America/New_York"
  | "America/Bogota"
  | "America/Caracas"
  | "America/Santiago"
  | "America/Buenos_Aires"
  | "America/Sao_Paulo"
  | "Atlantic/South_Georgia"
  | "Atlantic/Azores"
  | "Atlantic/Cape_Verde"
  | "Europe/London"
  | "Europe/Berlin"
  | "Africa/Lagos"
  | "Europe/Athens"
  | "Africa/Cairo"
  | "Europe/Moscow"
  | "Asia/Riyadh"
  | "Asia/Dubai"
  | "Asia/Baku"
  | "Asia/Karachi"
  | "Asia/Tashkent"
  | "Asia/Calcutta"
  | "Asia/Dhaka"
  | "Asia/Almaty"
  | "Asia/Jakarta"
  | "Asia/Bangkok"
  | "Asia/Shanghai"
  | "Asia/Singapore"
  | "Asia/Tokyo"
  | "Asia/Seoul"
  | "Australia/Brisbane"
  | "Australia/Sydney"
  | "Pacific/Guam"
  | "Pacific/Noumea"
  | "Pacific/Auckland"
  | "Pacific/Fiji";

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    customers: Customer;
    quotes: Quote;
    bookings: Booking;
    jobs: Job;
    "job-events": JobEvent;
    payments: Payment;
    refunds: Refund;
    "webhook-events": WebhookEvent;
    users: User;
    "payload-kv": PayloadKv;
    "payload-locked-documents": PayloadLockedDocument;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    customers: CustomersSelect<false> | CustomersSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    "job-events": JobEventsSelect<false> | JobEventsSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    refunds: RefundsSelect<false> | RefundsSelect<true>;
    "webhook-events": WebhookEventsSelect<false> | WebhookEventsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    "payload-kv": PayloadKvSelect<false> | PayloadKvSelect<true>;
    "payload-locked-documents":
      PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    "payload-preferences":
      PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    "payload-migrations": PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  email: string;
  name: string;
  phone: string;
  marketingConsent?: boolean | null;
  marketingConsentAt?: string | null;
  stripeCustomerId?: string | null;
  /**
   * PRD-07: excluded from reports and TfL exports.
   */
  isTest?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Priced journeys awaiting checkout. Expire after 30 minutes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: number;
  /**
   * Opaque, random. The only thing that travels in the URL between steps.
   */
  token: string;
  status: "open" | "converted" | "expired";
  /**
   * Set to 30 minutes after creation (BK-08).
   */
  expiresAt: string;
  /**
   * The journey as asked for: service mode, legs, party, extras. A FunnelParams snapshot.
   */
  request:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * What we quoted, per vehicle class, with the line breakdown.
   */
  results:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * The chosen vehicle's total, in integer pence (NFR-08). Denormalised from `results` so the admin can sort on it.
   */
  totalPence: number;
  /**
   * Set once step 3 collects the passenger details.
   */
  customer?: (number | null) | Customer;
  /**
   * The Stripe Checkout Session paying for this quote (PAY-01). One per quote, ever: reusing it is what stops a reloaded payment page opening a second session that could be paid twice.
   */
  stripeCheckoutSessionId?: string | null;
  /**
   * PRD-07: excluded from reports and TfL exports.
   */
  isTest?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Website orders. Created by checkout only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  /**
   * CL-XXXXXX, from domain/booking/reference.ts. Read down the phone, so the alphabet excludes I, L, O and U.
   */
  reference: string;
  status: "pending_payment" | "confirmed" | "cancelled" | "completed" | "expired";
  customer: number | Customer;
  quote?: (number | null) | Quote;
  /**
   * Only set when the booker is not the travelling passenger (BK-04).
   */
  bookerName?: string | null;
  bookerPhone?: string | null;
  bookerEmail?: string | null;
  subtotalPence: number;
  discountPence: number;
  totalPence: number;
  /**
   * What the customer was shown and agreed to, line by line. Kept even if the pricing engine changes afterwards — CMP-02 requires the agreed fare to be recorded.
   */
  priceSnapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Which version of the terms was accepted at checkout (CMP-11). Needed to answer 'what did they agree to?' months later.
   */
  termsVersion?: string | null;
  /**
   * Hash of the magic-link token (BK-07). The token itself is emailed and never stored.
   */
  manageTokenHash?: string | null;
  cancelledAt?: string | null;
  cancelReason?: string | null;
  /**
   * DATA-11: finance and TfL records are archived, never deleted. Kept 12 months (TfL) and 6 years (accounting).
   */
  archivedAt?: string | null;
  /**
   * PRD-07: excluded from reports and TfL exports.
   */
  isTest?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every job, every source. The TfL booking register (CMP-03).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  /**
   * J-000001
   */
  reference: string;
  /**
   * Required and immutable (§2). Website jobs come only from checkout.
   */
  source: "website" | "supplier" | "phone" | "whatsapp" | "email" | "account" | "other";
  booking?: (number | null) | Booking;
  /**
   * One job per leg. Unique per (booking, leg).
   */
  leg?: ("outbound" | "return") | null;
  returnOfJob?: (number | null) | Job;
  pickupAt: string;
  pickupAddress: string;
  pickupLat?: number | null;
  pickupLng?: number | null;
  dropoffAddress?: string | null;
  dropoffLat?: number | null;
  dropoffLng?: number | null;
  viaStops?:
    | {
        address: string;
        lat?: number | null;
        lng?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * So the office can check the arrival time before dispatch, and so a controller can search on it (JOB-11). No automatic flight tracking exists.
   */
  flightNumber?: string | null;
  flightArrivalAt?: string | null;
  distanceM?: number | null;
  durationS?: number | null;
  /**
   * Hourly hire only: how long the car is booked for.
   */
  hours?: number | null;
  vehicleClassSlug: string;
  passengers: number;
  largeBags: number;
  smallBags: number;
  leadName: string;
  leadPhone: string;
  leadEmail?: string | null;
  meetAndGreet?: boolean | null;
  /**
   * What goes on the driver's board. The travelling passenger's name, not the booker's.
   */
  nameBoardText?: string | null;
  extras?:
    | {
        slug: string;
        quantity: number;
        unitPricePence: number;
        id?: string | null;
      }[]
    | null;
  status:
    | "unassigned"
    | "assigned"
    | "driver_confirmed"
    | "completed"
    | "no_show"
    | "cancelled";
  /**
   * Copied onto the job at assignment, not looked up later (CMP-03). The register must show the number that applied on the day.
   */
  driverPhvNo?: string | null;
  vehicleReg?: string | null;
  /**
   * Null for website jobs — the system took the booking.
   */
  takenByUser?: (number | null) | User;
  takenAt?: string | null;
  dispatchedByUser?: (number | null) | User;
  dispatchedAt?: string | null;
  subcontractorName?: string | null;
  completedAt?: string | null;
  cancelledAt?: string | null;
  cancelReason?: string | null;
  /**
   * CMP-02: a fare must be agreed before the journey and recorded. Integer pence (NFR-08).
   */
  customerPricePence: number;
  paymentMethod: "web_prepaid" | "supplier" | "cash" | "card_link" | "bank" | "account";
  /**
   * Stripe's fee, from the webhook.
   */
  paymentFeePence?: number | null;
  /**
   * JOB-07: website jobs lock price, customer and route. Changes go through the booking's amend flow.
   */
  locked?: boolean | null;
  driverNotes?: string | null;
  internalNotes?: string | null;
  notifyPassenger?: boolean | null;
  archivedAt?: string | null;
  /**
   * PRD-07: excluded from reports and TfL exports.
   */
  isTest?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: "owner" | "controller" | "accounts" | "editor";
  active?: boolean | null;
  lastLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: "users";
}
/**
 * Append-only history. Rows are never edited or removed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-events".
 */
export interface JobEvent {
  id: number;
  job: number | Job;
  type:
    "created" | "updated" | "assigned" | "unassigned" | "status_changed" | "message_sent";
  field?: string | null;
  oldValue?: string | null;
  newValue?: string | null;
  actorType: "user" | "system" | "customer";
  actorUser?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  booking?: (number | null) | Booking;
  job?: (number | null) | Job;
  stripePaymentIntentId: string;
  amountPence: number;
  /**
   * Stripe's fee, needed for net revenue (§7).
   */
  feePence?: number | null;
  status: string;
  kind: "initial" | "amendment" | "post_trip" | "payment_link";
  /**
   * The Stripe object as received, for reconciliation.
   */
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "refunds".
 */
export interface Refund {
  id: number;
  payment: number | Payment;
  stripeRefundId: string;
  amountPence: number;
  reason?: string | null;
  createdByUser?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Idempotency ledger. One row per event we have handled.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-events".
 */
export interface WebhookEvent {
  id: number;
  provider: "stripe" | "whatsapp";
  eventId: string;
  type: string;
  processedAt?: string | null;
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: "customers";
        value: number | Customer;
      } | null)
    | ({
        relationTo: "quotes";
        value: number | Quote;
      } | null)
    | ({
        relationTo: "bookings";
        value: number | Booking;
      } | null)
    | ({
        relationTo: "jobs";
        value: number | Job;
      } | null)
    | ({
        relationTo: "job-events";
        value: number | JobEvent;
      } | null)
    | ({
        relationTo: "payments";
        value: number | Payment;
      } | null)
    | ({
        relationTo: "refunds";
        value: number | Refund;
      } | null)
    | ({
        relationTo: "webhook-events";
        value: number | WebhookEvent;
      } | null)
    | ({
        relationTo: "users";
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: "users";
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: "users";
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  phone?: T;
  marketingConsent?: T;
  marketingConsentAt?: T;
  stripeCustomerId?: T;
  isTest?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  token?: T;
  status?: T;
  expiresAt?: T;
  request?: T;
  results?: T;
  totalPence?: T;
  customer?: T;
  stripeCheckoutSessionId?: T;
  isTest?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  reference?: T;
  status?: T;
  customer?: T;
  quote?: T;
  bookerName?: T;
  bookerPhone?: T;
  bookerEmail?: T;
  subtotalPence?: T;
  discountPence?: T;
  totalPence?: T;
  priceSnapshot?: T;
  termsVersion?: T;
  manageTokenHash?: T;
  cancelledAt?: T;
  cancelReason?: T;
  archivedAt?: T;
  isTest?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  reference?: T;
  source?: T;
  booking?: T;
  leg?: T;
  returnOfJob?: T;
  pickupAt?: T;
  pickupAddress?: T;
  pickupLat?: T;
  pickupLng?: T;
  dropoffAddress?: T;
  dropoffLat?: T;
  dropoffLng?: T;
  viaStops?:
    | T
    | {
        address?: T;
        lat?: T;
        lng?: T;
        id?: T;
      };
  flightNumber?: T;
  flightArrivalAt?: T;
  distanceM?: T;
  durationS?: T;
  hours?: T;
  vehicleClassSlug?: T;
  passengers?: T;
  largeBags?: T;
  smallBags?: T;
  leadName?: T;
  leadPhone?: T;
  leadEmail?: T;
  meetAndGreet?: T;
  nameBoardText?: T;
  extras?:
    | T
    | {
        slug?: T;
        quantity?: T;
        unitPricePence?: T;
        id?: T;
      };
  status?: T;
  driverPhvNo?: T;
  vehicleReg?: T;
  takenByUser?: T;
  takenAt?: T;
  dispatchedByUser?: T;
  dispatchedAt?: T;
  subcontractorName?: T;
  completedAt?: T;
  cancelledAt?: T;
  cancelReason?: T;
  customerPricePence?: T;
  paymentMethod?: T;
  paymentFeePence?: T;
  locked?: T;
  driverNotes?: T;
  internalNotes?: T;
  notifyPassenger?: T;
  archivedAt?: T;
  isTest?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-events_select".
 */
export interface JobEventsSelect<T extends boolean = true> {
  job?: T;
  type?: T;
  field?: T;
  oldValue?: T;
  newValue?: T;
  actorType?: T;
  actorUser?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  booking?: T;
  job?: T;
  stripePaymentIntentId?: T;
  amountPence?: T;
  feePence?: T;
  status?: T;
  kind?: T;
  raw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "refunds_select".
 */
export interface RefundsSelect<T extends boolean = true> {
  payment?: T;
  stripeRefundId?: T;
  amountPence?: T;
  reason?: T;
  createdByUser?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-events_select".
 */
export interface WebhookEventsSelect<T extends boolean = true> {
  provider?: T;
  eventId?: T;
  type?: T;
  processedAt?: T;
  payload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  active?: T;
  lastLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: "full";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module "payload" {
  export interface GeneratedTypes extends Config {}
}
